# -*- coding: utf-8 -*-
"""mean_var_std.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MTao68BIylBoKWDZjep4284VbM1K8bj
"""

# Mean-variance-standard-deviation calculator

import numpy as np

def calculate(list):
  if len(list) != 9:
    raise ValueError("List must contain nine numbers.")
  else:
    params=list
    arr=np.array(params)
    arr=arr.reshape((3,3))
    dic={
    'mean': [(np.mean(arr,axis=0)).tolist(), np.mean(arr,axis=1).tolist(), arr.mean().tolist()],
    'variance': [np.var(arr,axis=0).tolist(), np.var(arr,axis=1).tolist(), arr.var().tolist()],
    'standard deviation': [np.std(arr,axis=0).tolist(), np.std(arr,axis=1).tolist(), arr.std().tolist()],
    'max': [np.max(arr,axis=0).tolist(), np.max(arr,axis=1).tolist(), arr.max().tolist()],
    'min': [np.min(arr,axis=0).tolist(), np.min(arr,axis=1).tolist(), arr.min().tolist()],
    'sum': [np.sum(arr,axis=0).tolist(), np.sum(arr,axis=1).tolist(), arr.sum().tolist()]
  }
  return dic