# -*- coding: utf-8 -*-
"""sea_level_predictor.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGeSME7nRQ1XJYml0FmUOcByk3LDwdqq
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress

def draw_plot():
    # Read data from file
    df = pd.read_csv('epa-sea-level.csv')

    # Create scatter plot
    plt.scatter(df['Year'], df['CSIRO Adjusted Sea Level'], label='Original Data', color='blue')

    # Create first line of best fit
    linear = linregress(df['Year'], df['CSIRO Adjusted Sea Level'])
    intercept = linear.intercept
    slope = linear.slope

    extended_years = list(range(1880, 2051))  # Includes original and extended years
    predicted_sea_levels = [intercept + slope * year for year in extended_years]

    # Plot the first predicted line
    plt.plot(extended_years, predicted_sea_levels, label='First Line of Best Fit', color='red')

    # Create second line of best fit (data from 2000 onward)
    df_second = df[df['Year'] >= 2000].copy()
    plt.scatter(df_second['Year'], df_second['CSIRO Adjusted Sea Level'], label='Data from 2000', color='green')

    linear_second = linregress(df_second['Year'], df_second['CSIRO Adjusted Sea Level'])
    intercept_second = linear_second.intercept
    slope_second = linear_second.slope

    years_second = list(range(2000, 2051))
    predicted_sea_levels_second = [intercept_second + slope_second * year for year in years_second]

    # Plot the second predicted line
    plt.plot(years_second, predicted_sea_levels_second, label='Second Line of Best Fit', color='orange')

    # Add labels and title
    plt.xlabel('Year')
    plt.ylabel('Sea Level (inches)')
    plt.title('Rise in Sea Level')
    plt.legend()

    # Save plot and return data for testing (DO NOT MODIFY)
    plt.savefig('sea_level_plot.png')
    return plt.gca()

# Call the function to test
draw_plot()